Repository truenas/ixdiagnose, pull requests merged in 2023-09, with the labels that each got.

#62 NAS-124070 / 24.04 / Remove websocket message logging as it leaks private data
  ixdiagnose/plugins/system.py
Labels: backport-23.10, backport-23.10-RC.1

#65 NAS-124197 / 24.04 / smb_shares is not a json file, use proper extension
  ixdiagnose/plugins/smb.py
Labels: jira

#68 NAS-124249 / 24.04 / Remove core.get_jobs from system plugin
  ixdiagnose/plugins/system.py
Labels: jira, backport-23.10

#61 NAS-121797 / 24.04 / CLI for ixdiagnose
  .github/workflows/test_coverage.yml
  docs/filesystem_heirarchy.md
  ixdiagnose/artifact.py
  ixdiagnose/cli.py
  ixdiagnose/config.py
  ixdiagnose/main.py
  ixdiagnose/plugin.py
  ixdiagnose/test/pytest/integration/test_artifacts.py
  ixdiagnose/test/pytest/integration/test_plugins.py
  ixdiagnose/test/pytest/unit/run/test_cli.py
  setup.py
Labels: backport-23.10

#72 NAS-124270 / 24.04 / Add system.info
  ixdiagnose/plugins/system.py
Labels: jira, backport-23.10

#74 NAS-124272 / 24.04 / add procfs plugin and capture spl directory tree
  ixdiagnose/artifacts/factory.py
  ixdiagnose/artifacts/proc.py
  ixdiagnose/plugins/zfs.py
  ixdiagnose/test/pytest/unit/plugins/assets/kstat_output.txt
  ixdiagnose/test/pytest/unit/plugins/test_zfs.py
Labels: backport-23.10

#76 NAS-124274 / 24.04 / add 2nd -s to show interface errors
  ixdiagnose/plugins/network.py
Labels: backport-23.10

#78 NAS-124294 / 24.04 / Retrieve 2fa configuration details in debug
  ixdiagnose/plugins/factory.py
  ixdiagnose/plugins/two_factor_auth.py
Labels: jira, backport-23.10

#70 NAS-124258 / 24.04 / Retrieve k8s backups information in debug as well
  ixdiagnose/plugins/kubernetes.py
Labels: jira, backport-23.10
