Repository truenas/ixdiagnose, pull requests merged in 2023-08, with the labels that each got.

#35 NAS-123439 / 24.04 / Add certificate plugin to debug
  ixdiagnose/plugins/certificates.py
  ixdiagnose/plugins/factory.py
Labels: jira, backport-23.10, backport-23.10-BETA.1

#38 NAS-123567 / 24.04 / Fix dataset_list header
  ixdiagnose/plugins/zfs.py
Labels: backport-23.10

#39 NAS-123566 / 24.04 / Don't get zfs snapshots details
  ixdiagnose/plugins/zfs.py
Labels: backport-23.10

#42 NAS-123564 / 24.04 / Data protection tasks dump
  ixdiagnose/plugins/cloud_backup.py
  ixdiagnose/plugins/cloud_sync.py
  ixdiagnose/plugins/factory.py
  ixdiagnose/plugins/rsync.py
Labels: backport-23.10

#46 NAS-123590 / 24.04 / add VMPrerequisite to prevent log spam
  ixdiagnose/plugins/prerequisites/__init__.py
  ixdiagnose/plugins/prerequisites/vm.py
  ixdiagnose/plugins/vm.py
Labels: backport-23.10

#48 NAS-123595 / 24.04 / Fix VMPrerequisite
  ixdiagnose/plugins/prerequisites/vm.py
Labels: jira, backport-23.10

#51 NAS-123643 / 24.04 / Add top output to separate file
  ixdiagnose/plugins/system.py
Labels: backport-23.10

#50 NAS-123640 / 24.04 / Add cronjob plugin
  ixdiagnose/plugins/cronjob.py
  ixdiagnose/plugins/factory.py
Labels: backport-23.10

#57 NAS-123774 / 24.04 / add InitShutDownScript plugin
  ixdiagnose/plugins/factory.py
  ixdiagnose/plugins/initshutdown_scripts.py
Labels: backport-23.10

#59 NAS-123827 / 24.04 / add core.get_jobs to plugins
  ixdiagnose/plugins/factory.py
  ixdiagnose/plugins/jobs.py
Labels: backport-23.10
