Repository truenas/ixdiagnose, pull requests merged in 2023-12, with the labels that each got.

#131 NAS-125734 / 24.04 / add Containers plugin
  ixdiagnose/plugins/containers.py
  ixdiagnose/plugins/factory.py
Labels: backport-23.10.2

#130 NAS-125669 / 24.04 / Add swap configuration in system plugin
  ixdiagnose/plugins/system.py
Labels: jira, backport-23.10.2

#134 NAS-125825 / 24.04 / Redact nslcd.conf
  ixdiagnose/plugins/ldap.py
Labels: backport-23.10.2

#136 NAS-125872 / 24.04 / Add plugin for privilege-related info
  ixdiagnose/plugins/factory.py
  ixdiagnose/plugins/rbac.py
Labels: jira, backport-23.10.2

#138 NAS-125874 / 24.04 / Remove clustering from debug
  ixdiagnose/plugins/clustering.py
  ixdiagnose/plugins/factory.py
Labels: jira

#139 NAS-125815 / 24.04 / Add enclosure2 query output to debug
  ixdiagnose/plugins/hardware.py
Labels: backport-23.10.2

#141 NAS-125923 / 24.04 / Add root password disabled override info to debug
  ixdiagnose/plugins/rbac.py
Labels: jira, backport-23.10.2

#143 NAS-125926 / 24.04 / Expand rbac-related debug information
  ixdiagnose/plugins/rbac.py
Labels: jira
