Repository truenas/ixdiagnose, pull requests merged in 2023-10, with the labels that each got.

#83 NAS-124407 / 24.04 / Add text file with number of NFS clients by type
  ixdiagnose/plugins/nfs.py
Labels: jira, backport-23.10

#82 NAS-124248 / 24.04 / Remove password key when retrieving VM devices details
  ixdiagnose/plugins/vm.py
  ixdiagnose/test/pytest/unit/test_formatter/test_formatter.py
  ixdiagnose/utils/formatter.py
Labels: backport-23.10

#89 NAS-124303 / 24.04 / Add glob based item to collect artifacts
  ixdiagnose/artifacts/items/__init__.py
  ixdiagnose/artifacts/items/glob.py
  ixdiagnose/test/pytest/integration/items/__init__.py
  ixdiagnose/test/pytest/integration/items/test_glob.py
Labels: backport-23.10.0, backport-23.10.1

#88 NAS-124501 / 24.04 / Update README for ixdiagnose
  README.md
Labels: jira, backport-23.10.0, backport-23.10.1

#96 NAS-124597 / 24.04 / Collect sysfs modules parameters
  ixdiagnose/artifacts/factory.py
  ixdiagnose/artifacts/sys_parameters.py
Labels: jira, backport-23.10.0, backport-23.10.1

#99 NAS-124585 / 24.04 / Make sure we set correct perms to prevent access
  ixdiagnose/run.py
  ixdiagnose/test/pytest/unit/run/test_debug.py
Labels: backport-23.10.0, backport-23.10.1

#102 Save additional iSCSI configuration
  ixdiagnose/plugins/iscsi.py
Labels: backport-23.10.0

#103 NAS-124706 / 23.10.1 / Save additional iSCSI configuration (by bmeagherix)
  ixdiagnose/plugins/iscsi.py
Labels: backport-23.10.0

#106 NAS-124796 / 24.04 / Add partition type name and size to `lsblk`
  ixdiagnose/plugins/hardware.py
Labels: jira, backport-23.10.1

#107 NAS-124772 / 24.04 / Retrieve iommu groups information in debug
  ixdiagnose/plugins/vm.py
Labels: jira, backport-23.10.1

#112 NAS-124922 / 24.04 / Bring back `zpool status -g`
  ixdiagnose/plugins/zfs.py
Labels: jira, backport-23.10.1
