Repository truenas/ixdiagnose, pull requests merged in 2023-11, with the labels that each got.

#114 NAS-124975 / 24.04 / Grab libvirt logs in debug
  ixdiagnose/artifacts/logs.py
Labels: jira, backport-23.10.1

#117 NAS-125087 / 24.04 / Add integration test for debug and compress path permissions
  ixdiagnose/test/pytest/integration/test_compress_debug.py
Labels: jira, backport-23.10.1

#120 NAS-125105 / 24.04 / Add docs for glob item type
  docs/artifacts/artifacts.md
  docs/artifacts/items/items.md
Labels: jira

#121 NAS-125145 / 24.04 / Add disk.query
  ixdiagnose/plugins/hardware.py
Labels: jira, backport-23.10.1

#123 NAS-125456 / 24.04 / Include `pool.query` in human-readable debug also
  ixdiagnose/plugins/zfs.py
Labels: jira, backport-23.10.1, backport-23.10.2
