Repository truenas/ixdiagnose, pull requests merged in 2024-12, with the labels that each got.

#250 NAS-132940 / 25.04 / fix zvol output when there are no zvols
  ixdiagnose/plugins/zfs.py
Labels: jira-low, backport-24.10.2

#252 NAS-133284 / 25.04 / add system.vendor info
  ixdiagnose/plugins/factory.py
  ixdiagnose/plugins/system_vendor.py
Labels: backport-24.10.2

#254 NAS-133336 / 25.04 / Add structured exception data to debug
  ixdiagnose/plugins/exceptions.py
  ixdiagnose/plugins/factory.py
Labels: jira
