Repository truenas/ixdiagnose, pull requests merged in 2024-08, with the labels that each got.

#206 NAS-130454 / 24.10 / Add audit details to debug
  ixdiagnose/plugins/audit.py
  ixdiagnose/plugins/factory.py
Labels: jira

#207 NAS-130557 / 24.10 / Grab debug information for apps
  ixdiagnose/plugins/apps.py
  ixdiagnose/plugins/factory.py
Labels: jira

#208 NAS-130585 / 25.04 / Exclude nvidia-related changes from `/usr` daatset diff
  ixdiagnose/plugins/system_state.py
  ixdiagnose/utils/command.py
Labels: backport-24.10-BETA.1, backport-24.10-RC.1

#211 NAS-130771 / 25.04 / Add RedactedFileMetric and use to redact iSCSI CHAP secrets
  ixdiagnose/plugins/iscsi.py
  ixdiagnose/plugins/metrics/__init__.py
  ixdiagnose/plugins/metrics/file.py
  ixdiagnose/test/pytest/unit/metrics/assets/redacted_file_metric_scst_input.txt
  ixdiagnose/test/pytest/unit/metrics/assets/redacted_file_metric_scst_output.txt
  ixdiagnose/test/pytest/unit/metrics/test_redacted_file_metric.py
  ixdiagnose/test/pytest/unit/utils.py
Labels: jira, backport-24.10-RC.1

#213 NAS-130778 / 25.04 / Redact passdb_list results
  ixdiagnose/plugins/smb.py
Labels: jira

#214 NAS-130812 / 25.04 / Fix `core.get_jobs` output
  ixdiagnose/plugins/jobs.py
Labels: jira, backport-24.10-BETA.1, backport-24.10-RC.1

#218 NAS-130858 / 25.04 / remove file exclusion from ixdiagnose on enterprise systems
  ixdiagnose/plugins/metrics/command.py
  ixdiagnose/plugins/system_state.py
  ixdiagnose/utils/command.py
Labels: backport-24.10-RC.1

#217 NAS-130590 / 25.04 / add truenas_verify.log
  ixdiagnose/artifacts/logs.py
Labels: backport-24.10-RC.1
