Repository truenas/ixdiagnose, pull requests merged in 2024-03, with the labels that each got.

#170 NAS-127445 / 24.10 / Make sure we capture samba log directories
  ixdiagnose/artifacts/base.py
  ixdiagnose/artifacts/items/__init__.py
  ixdiagnose/artifacts/items/base.py
  ixdiagnose/artifacts/items/pattern.py
  ixdiagnose/artifacts/logs.py
  ixdiagnose/test/pytest/integration/items/test_directory_pattern.py
  ixdiagnose/test/pytest/integration/test_artifacts.py
Labels: backport-23.10.3, backport-24.04.0

#171 NAS-127625 / 24.10 / `gather_update_failed` is no longer needed
  ixdiagnose/plugins/system.py
Labels: skip jira status

#176 NAS-128061 / 24.10 / Retrieve bootenv details in debug
  ixdiagnose/plugins/system_state.py
Labels: jira, backport-24.04.0
