Repository truenas/ixdiagnose, pull requests merged in 2024-11, with the labels that each got.

#238 NAS-132314 / 25.04 / add virtualization info
  ixdiagnose/plugins/hardware.py
Labels: backport-24.10.1

#240 NAS-132315 / 25.04 / fix minor cosmetic ixnvdimm output
  ixdiagnose/plugins/hardware.py
Labels: jira-low, backport-24.10.1

#242 NAS-132534 / 25.04 / Add jbof and rdma
  ixdiagnose/plugins/hardware.py
  ixdiagnose/plugins/network.py
Labels: jira-low, backport-24.10.1

#245 NAS-132562 / 25.04 / Update LDAP config collection for sssd
  ixdiagnose/plugins/ldap.py
Labels: jira, backport-24.10.1

#244 NAS-132555 / 25.04 / Include snmp in plugins diagnostic.
  ixdiagnose/plugins/factory.py
  ixdiagnose/plugins/snmp.py
Labels: jira, backport-24.10.1

#248 NAS-132548 / 25.04 / Add NVME plugin
  ixdiagnose/plugins/factory.py
  ixdiagnose/plugins/nvme.py
  ixdiagnose/plugins/smart.py
Labels: backport-24.10.1
