Repository truenas/ixdiagnose, pull requests merged in 2024-01, with the labels that each got.

#146 NAS-126019 / 24.04 / Collect job logs
  ixdiagnose/artifacts/logs.py
Labels: jira, backport-23.10.2

#148 NAS-126012 / 24.04 / Add ability to ignore files/dirs for directory item
  ixdiagnose/artifacts/items/directory.py
  ixdiagnose/artifacts/proc.py
  ixdiagnose/test/pytest/integration/test_artifacts.py
Labels: backport-23.10.2

#150 NAS-126861 / 24.10 / Fix share ACL output in debug
  ixdiagnose/plugins/smb.py
Labels: backport-24.04-RC.1, backport-24.04-BETA.1

#153 NAS-126889 / 24.10 / Add missing information to AD debug
  ixdiagnose/plugins/active_directory.py
Labels: jira, backport-24.04-RC.1, backport-24.04-BETA.1, backport-23.10.2

#158 NAS-126908 / 24.10 / Add /proc/net/bonding dir to debug
  ixdiagnose/artifacts/items/directory.py
  ixdiagnose/artifacts/proc.py
  ixdiagnose/test/pytest/integration/test_artifacts.py
Labels: backport-24.04-RC.1, backport-23.10.2
