Repository truenas/ixdiagnose, pull requests merged in 2024-10, with the labels that each got.

#227 NAS-131668 / 25.04 / Grab serialized zpool status output in debug
  ixdiagnose/plugins/zfs.py
Labels: jira, backport-24.10.0

#229 NAS-132010 / 25.04 / add zvols to zvol_config.txt
  ixdiagnose/plugins/zfs.py
Labels: backport-24.10.1, backport-24.10.0

#232 NAS-132055 / 25.04 / Fix zfs get acl unit test
  ixdiagnose/test/pytest/unit/plugins/test_zfs.py
Labels: jira, backport-24.10.1

#234 NAS-132049 / 25.04 / add ixnvdimm output to debug
  ixdiagnose/plugins/hardware.py
Labels: backport-24.10.1
