Repository truenas/ixdiagnose, pull requests merged in 2024-04, with the labels that each got.

#179 NAS-128134 / 24.10 / Get chart release stats in debug
  ixdiagnose/plugins/kubernetes.py
Labels: jira, backport-24.04.0

#180 NAS-128135 / 24.10 / Add UPS plugin
  ixdiagnose/plugins/factory.py
  ixdiagnose/plugins/ups.py
Labels: jira, backport-24.04.0

#183 NAS-128223 / 24.10 / add /data/update.failed
  ixdiagnose/plugins/system_state.py
Labels: backport-24.04.1, backport-24.04.0

#186 NAS-128235 / 24.10 / Revert "NAS-128223 / 24.10 / add /data/update.failed"
  ixdiagnose/plugins/system_state.py
Labels: jira
