Repository truenas/ixdiagnose, pull requests merged in 2025-05, with the labels that each got.

#281 NAS-135737 / 25.10 / Add raw incus instance information
  ixdiagnose/plugins/virt.py
Labels: backport-25.04.2, jira-high, backport-25.04.1

#280 NAS-135636 / 25.10 / Add system security config to debug
  ixdiagnose/plugins/system.py
Labels: backport-25.04.2, jira, backport-25.04.1

#286 NAS-135769 / 25.10 / Add sssd logs to artifacts.
  ixdiagnose/artifacts/logs.py
Labels: backport-25.04.2, jira

#289 NAS-135911 / 25.10 / Add output of `ethtool -m` to network plugin
  ixdiagnose/plugins/metrics/base.py
  ixdiagnose/plugins/metrics/python.py
  ixdiagnose/plugins/network.py
  ixdiagnose/utils/middleware.py
Labels: backport-25.04.2

#288 NAS-136081 / 25.10 / Remove cloudsync provider secrets from debug
  ixdiagnose/plugins/cloud_sync.py
Labels: backport-25.04.2, jira-high
