Repository truenas/ixdiagnose, pull requests merged in 2025-02, with the labels that each got.

#259 NAS-134057 / 25.10 / Remove failing deb action
  .github/workflows/ci.yml
Labels: jira

#258 NAS-133878 / 25.10 / Retrieve TNC info in debug
  ixdiagnose/artifacts/logs.py
  ixdiagnose/plugins/factory.py
  ixdiagnose/plugins/truenas_connect.py
Labels: jira, backport-25.04-RC.1, backport-25.04-BETA.1

#262 NAS-133958 / 25.10 / Remove legacy VM usages from ixdiagnose
  ixdiagnose/artifacts/logs.py
  ixdiagnose/plugins/factory.py
  ixdiagnose/plugins/vm.py
Labels: backport-25.04-RC.1

#264 NAS-133968 / 25.10 / Add truenas_verify data to audit plugin.
  ixdiagnose/plugins/audit.py
Labels: backport-25.04-RC.1

#266 NAS-133969 / 25.10 / Include audit SYSTEM events
  ixdiagnose/cli.py
  ixdiagnose/config.py
  ixdiagnose/plugins/audit.py
Labels: backport-25.04-RC.1
