Repository truenas/ixdiagnose, pull requests merged in 2025-03, with the labels that each got.

#268 NAS-134506 / 25.10 / Add ixdiagnose virt plugin
  ixdiagnose/artifacts/logs.py
  ixdiagnose/plugins/factory.py
  ixdiagnose/plugins/virt.py
Labels: jira-high, backport-25.04-RC.1

#271 NAS-134761 / 25.10 / Redact virt instance output
  ixdiagnose/plugins/virt.py
Labels: jira-high, backport-25.04.0

#273 NAS-134820 / 25.10 / Filter out SERVICE_START and SERVICE_STOP audit messages
  ixdiagnose/plugins/audit.py
Labels: backport-25.04.0

#275 NAS-134894 / 25.10 / Improve SMART capture function
  ixdiagnose/plugins/smart.py
  ixdiagnose/test/pytest/unit/plugins/test_smart_output.py
Labels: jira-low

#276 NAS-134927 / 25.10 / Add `smartmontools` dependency
  debian/control
Labels: skip jira status
