Repository truenas/ixdiagnose, pull requests merged in 2025-08, with the labels that each got.

#306 NAS-137047 / 26.04 / sysfs_parameters: Use relative_to for clean structure
  ixdiagnose/artifacts/sys_parameters.py
Labels: jira-low

#311 NAS-137237 / 26.04 / Allow executing a plugin selectively
  ixdiagnose/cli.py
  ixdiagnose/config.py
  ixdiagnose/plugin.py
  ixdiagnose/test/pytest/unit/run/test_cli.py
Labels: jira

#312 NAS-136827 / 26.04 / Add jbof_view to hardware plugin
  ixdiagnose/plugins/hardware.py
  ixdiagnose/plugins/prerequisites/__init__.py
  ixdiagnose/plugins/prerequisites/jbof.py
Labels: backport-25.10-RC.1
